In [19]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

In [20]:
df=pd.read_csv(r'DATASET.csv')
df.head(10)

,Type,User_id,Product Name,Color,Manufacturing Location,Seller,Location,Price,Season,Quantity,Rating,Review
0,Teracotta,1,Teracotta 1,Brown,Nabadwip,B2,Siliguri,284.50,Autumn,28,4.1,Good
1,Leather Goods,1,Santiniketan Leather 5,Rainbow,Santiniketan,A2,Ultodanga,331.49,Summer,11,4.0,Good
2,Saree,1,Baluchari Saree 3,Light Blue,Bishnupur,B1,Naihati,357.07,Summer,11,3.8,Moderate
3,Saree,1,Baluchari Saree 5,Yellow,Bishnupur,B1,Purulia,452.76,Winter,16,3.9,Moderate
4,Saree,1,Santipur Tanter Saree 5,Brown,Santipur,A1,Duttapukur,681.99,Rainy,17,4.0,Good
5,Kathi,1,Madur 1,Red,Paschim Medinipur,A3,Nabadwip,189.60,Winter,35,3.5,Moderate
6,Saree,1,Baluchari Saree 4,Green,Bishnupur,B1,Raniganj,471.08,Summer,12,4.0,Good
7,Saree,1,Santipur Tanter Saree 7,Orange,Santipur,A1,Nadia,547.99,Winter,24,4.3,Excellent
8,Kathi,2,Madur 1,Light Brown,Paschim Medinipur,A3,Bethuadahari,198.60,Automn,28,3.9,Moderate
9,Teracotta,2,Teracotta 1,Brown,Nabadwip,B2,Asansol,223.90,Summer,45,3.9,Moderate

In [21]:
for i in df.columns:
    print(df[i].nunique())

5
100
54
16
6
6
33
685
6
45
11
3

In [22]:
arr=(df['Product Name'].unique())
for i in arr:
    print(i)

Teracotta 1
Santiniketan Leather 5
Baluchari Saree 3
Baluchari Saree 5
Santipur Tanter Saree 5
Madur 1
Baluchari Saree 4
Santipur Tanter Saree 7
Baluchari Saree 7
Santipur Tanter Saree 1
Chau Mask 1
Santiniketan Leather 1
Santiniketan Leather 6
Santiniketan Leather 8
Baluchari Saree 8
Santipur Tanter Saree 4
Santipur Tanter Saree 10
Santiniketan Leather 2
Baluchari Saree 2
Baluchari Saree 6
Baluchari Saree 10
Santipur Tanter Saree 6
Chau Mask 8
Santiniketan Leather 4
Santiniketan Leather 9
Santipur Tanter Saree 3
Santipur Tanter Saree 9
Madur 2
Baluchari Saree 1
Santipur Tanter Saree 2
Teracotta 2
Santiniketan Leather 3
Santipur Tanter Saree 8
Madur 3
Chau Mask 2
Teracotta 3
Santiniketan Leather 7
Santiniketan Leather 10
Chau Mask 7
Madur 4
Baluchari Saree 9
Madur 5
Teracotta 4
Teracotta 5
Madur 6
Teracotta 6
Madur 7
Chau Mask 5
Teracotta 7
Chau Mask 3
Madur 8
Teracotta 8
Chau Mask 4
Chau Mask 6

In [23]:
rating_counts = pd.DataFrame(df["Product Name"].value_counts())
rating_counts.head()

                         Product Name
Teracotta 8                        38
Chau Mask 2                        38
Teracotta 6                        26
Teracotta 7                        20
Santipur Tanter Saree 4            20

In [24]:
user_product_df = df.pivot_table(index=["User_id"], columns=["Product Name"], values="Rating").fillna(0)

user_product_df.shape

(100, 54)

In [25]:
user_product_df.head(10)

Product Name,Baluchari Saree 1,Baluchari Saree 10,Baluchari Saree 2,Baluchari Saree 3,Baluchari Saree 4,Baluchari Saree 5,Baluchari Saree 6,Baluchari Saree 7,Baluchari Saree 8,Baluchari Saree 9,...,Santipur Tanter Saree 8,Santipur Tanter Saree 9,Teracotta 1,Teracotta 2,Teracotta 3,Teracotta 4,Teracotta 5,Teracotta 6,Teracotta 7,Teracotta 8
User_id,,,,,,,,,,,,,,,,,,,,,
1,0.00,0.0,0.0,3.8,4.0,3.9,0.0,0.0,0.0,0.0,...,0.0,0.0,4.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.00,0.0,0.0,0.0,0.0,0.0,0.0,3.9,0.0,0.0,...,0.0,0.0,3.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.9,0.0,...,0.0,0.0,4.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.00,0.0,4.3,0.0,0.0,0.0,0.0,0.0,4.2,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.00,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0.00,4.3,0.0,0.0,4.3,0.0,4.1,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,4.2,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,4.15,4.3,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,4.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,0.00,0.0,3.8,0.0,0.0,0.0,0.0,3.8,0.0,0.0,...,0.0,0.0,3.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [26]:
product_name = "Baluchari Saree 2"
product_name = user_product_df[product_name]

In [27]:
suggestions=user_product_df.corrwith(product_name).sort_values(ascending=False)

In [28]:
# for i in pred:
#     if i>0.5:
#         print(i)

In [29]:
sugg_df=pd.Series.to_frame(suggestions)

In [30]:
sugg_df[0]

Product Name
Baluchari Saree 2           1.000000
Santiniketan Leather 1      0.240957
Baluchari Saree 5           0.228730
Santipur Tanter Saree 1     0.176818
Madur 4                     0.135197
Teracotta 4                 0.118484
Santipur Tanter Saree 6     0.097149
Chau Mask 7                 0.090408
Santiniketan Leather 3      0.087534
Teracotta 2                 0.079645
Santipur Tanter Saree 5     0.074533
Madur 5                     0.069803
Santiniketan Leather 2      0.067681
Teracotta 8                 0.052024
Chau Mask 5                 0.045127
Chau Mask 4                 0.041246
Madur 6                     0.039518
Santiniketan Leather 7      0.037218
Baluchari Saree 9           0.037095
Santipur Tanter Saree 7     0.034539
Teracotta 3                 0.034495
Santipur Tanter Saree 4     0.028784
Chau Mask 2                 0.008766
Santipur Tanter Saree 8     0.006827
Santiniketan Leather 10     0.003777
Teracotta 6                -0.002033
Chau Mask 6                -0.003998
Santiniketan Leather 5     -0.005984
Baluchari Saree 4          -0.007081
Teracotta 5                -0.010293
Santiniketan Leather 6     -0.010587
Teracotta 7                -0.012250
Baluchari Saree 7          -0.013764
Madur 7                    -0.016281
Santipur Tanter Saree 3    -0.024032
Santiniketan Leather 9     -0.025995
Baluchari Saree 1          -0.032318
Baluchari Saree 8          -0.036613
Madur 2                    -0.040874
Chau Mask 8                -0.042671
Teracotta 1                -0.044130
Madur 3                    -0.056429
Chau Mask 3                -0.057346
Chau Mask 1                -0.069060
Madur 8                    -0.074228
Madur 1                    -0.081643
Santipur Tanter Saree 2    -0.092954
Santipur Tanter Saree 10   -0.100714
Santiniketan Leather 8     -0.102727
Santiniketan Leather 4     -0.102941
Baluchari Saree 10         -0.148552
Baluchari Saree 3          -0.160898
Baluchari Saree 6          -0.179256
Santipur Tanter Saree 9    -0.202809
Name: 0, dtype: float64

In [31]:
X = user_product_df.values.T
X.shape

(54, 100)

In [32]:
import sklearn
from sklearn.decomposition import TruncatedSVD

SVD = TruncatedSVD(n_components=10, random_state=42)
matrix = SVD.fit_transform(X)
matrix.shape

(54, 10)

In [33]:
import warnings
warnings.filterwarnings("ignore",category =RuntimeWarning)
corr = np.corrcoef(matrix)
corr.shape

(54, 54)

In [34]:
product_title = user_product_df.columns
product_title_list = list(product_title)
# print(product_title_list)
coffey_hands = product_title_list.index("Teracotta 1")

In [35]:
def recom_ItemBase():
    corr_coffey_hands  = corr[coffey_hands]
    return list(product_title[(corr_coffey_hands >= 0.7)])

In [36]:
import pickle
# Saving model to disk
pickle.dump(recom_ItemBase(), open('ItemBase.pkl','wb'))